# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0ec298ab657b629b404610eadb33eccbbf14c1b287cf1fc0f06c6ca18d311505c16f7d4f9764f378f8b64b6d21f6838e3bde719e206570fa9ab4671136be9418

test:
  secret_key_base: 489dea37d06554150678143f835fdf637c5a749edebc3a067ffb1930b9ce8ada96e131cd63e4d01a3bf3b6b3bd0a9418813c55dca83b3bb5b2f58c76177305de

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
